### ISSUE TITLE
MyVector parameterized constructor 

### ISSUE THREAD

**Issue by David-Huson** [uwf-fang/cop3014-examples#1]
The parameterized constructor in my-vector.cpp initializes the new array using the ```size``` variable instead of ```capacity``` as shown below:
<img width="352" alt="Screen Shot 2022-02-23 at 8 02 00 PM" src="https://user-images.githubusercontent.com/96091518/155443280-39cc90bc-d58e-4c74-8dc9-b8bd5a4a64f7.png">

**Comment by uwf-fang** [comment]
Fixed. 
commit: 0e444321
